# Generated by Django 2.1.5 on 2019-08-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='contnt',
            new_name='content',
        ),
    ]
